### ISSUE TITLE
Error with patches 256 and on increasing patches some of point cloud goes missing

### ISSUE THREAD

**Issue by avani17101** [ninaqy/PUGeo#5]
I am getting this error by running test(main.py) on a different point cloud 
![Screenshot from 2021-02-19 00-23-03](https://user-images.githubusercontent.com/33591258/108406741-cef05200-7248-11eb-9dcb-667631c673db.png)

When I change num_points to 1024 the error is gone, though some parts of my point cloud go missing.
Would appreciate any help on it.
The only change I made to code was num_points from 256 to 1024 and passing in num_shape_point according to points in my point cloud.

Upsampled point cloud
![Screenshot from 2021-02-19 00-33-38](https://user-images.githubusercontent.com/33591258/108407759-29d67900-724a-11eb-888e-5c1b3bf7b72f.png)

Original point cloud
![Screenshot from 2021-02-19 00-30-50](https://user-images.githubusercontent.com/33591258/108407633-001d5200-724a-11eb-9b03-3ff3f2fd4e87.png)

**Comment by ninaqy** [comment]
Hi, the code has been updated, please try again.
